FROM python:3.11-slim

WORKDIR /app

COPY Frontend/ ./Frontend/


RUN pip install --no-cache-dir -r Frontend/requirments.txt


WORKDIR /app/Frontend

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
