name: 'Discover Instances'
description: 'Scans for all existing customer-a containers'


outputs:
  instances:
    description: 'JSON array of instance configurations'
    value: ${{ steps.scan.outputs.instances }}


runs:
  using: "composite"
  steps:
    - name: Scan for instances
      id: scan
      shell: bash
      run: |
        echo "ðŸ” Discovering all customer-a instances..."
        echo ""
        
        CONTAINERS=$(docker ps -a --filter "name=customer-a-instance-" --format "{{.Names}}" 2>/dev/null | sort)
        
        if [ -z "$CONTAINERS" ]; then
          echo "â„¹ï¸  No existing containers found. Now using default (5 instances)"
          INSTANCES='[{"name":"customer-a-instance-1","port":8601,"num":1},{"name":"customer-a-instance-2","port":8602,"num":2},{"name":"customer-a-instance-3","port":8603,"num":3},{"name":"customer-a-instance-4","port":8604,"num":4},{"name":"customer-a-instance-5","port":8605,"num":5}]'
        else
          echo "âœ… Found existing containers:"
          echo "$CONTAINERS"
          echo ""
          
          INSTANCES="["
          FIRST=true
          
          for container in $CONTAINERS; do
            NUM=$(echo "$container" | sed 's/customer-a-instance-//')
            PORT=$((8600 + NUM))
            echo "  $container: Will use port $PORT"
            
            if [ "$FIRST" = "false" ]; then
              INSTANCES="${INSTANCES},"
            fi
            FIRST=false
            
            INSTANCES="${INSTANCES}{\"name\":\"$container\",\"port\":$PORT,\"num\":$NUM}"
          done
          
          INSTANCES="${INSTANCES}]"
        fi
        
        echo ""
        echo "ðŸ“Š Final Configuration: $INSTANCES"
        echo ""
        echo "instances=$INSTANCES" >> $GITHUB_OUTPUT
        
        exit 0
